"""The ONE harness-defined sub-agent: `course-reviewer`.

Reviews draft recap and concept relationships against the raw extracted source content.
"""

from typing import Optional
from google import genai
from src.config import DEFAULT_MODEL

SUBAGENT_NAME = "course-reviewer"

COURSE_REVIEWER_SYSTEM_PROMPT = """You are 'course-reviewer', a rigorous academic peer-reviewer and fact-checker sub-agent.

Your sole mission is to audit, cross-check, and refine a draft course recap and Mermaid concept diagram against the provided source course text extracted by the PDF Extraction MCP server.

Audit Directives:
1. Ground Truth & Factual Accuracy:
   - Check every topic explanation, formula, definition, and statement against the SOURCE GROUND TRUTH.
   - Correct any inaccuracies, misattributed concepts, or unsupported extrapolations.
   - If the draft hallucinated topics not in the course slides/material, remove them.

2. Concept Relationship & Diagram Verification:
   - Review the Mermaid concept relationship diagram (`flowchart TD`).
   - Ensure every concept node is genuinely part of the course.
   - Verify that dependency edges, prerequisite arrows, and hierarchical groupings reflect the logical relationships taught in the source material.
   - Remove any invented or misleading links.
   - Validate Mermaid syntax (proper node naming, enclosed in double quotes inside brackets e.g. NodeID["Concept Label"]).

3. Content Structure:
   - Preserve the clean structure:
     # [Course Title] - Comprehensive Course Recap
     ## Course Overview
     ## Topic-by-Topic Course Summary (modules/topics with Core Explanations, Key Definitions, Practical Implications)
     ## Concept Relationship Diagram (valid Mermaid code block)
   - Do NOT add quizzes, flashcards, cheat sheets, or other extraneous sections.

Output the complete, final corrected and polished course recap in Markdown.
"""


def review_recap_with_subagent(
    client: genai.Client,
    source_content: str,
    draft_recap: str,
    model: str = DEFAULT_MODEL,
) -> str:
    """Invoke the `course-reviewer` sub-agent to audit and refine the draft recap.

    Args:
        client: Initialized Google GenAI client.
        source_content: Raw text extracted from the course PDF via the MCP server.
        draft_recap: Initial recap generated by the main agent.
        model: Gemini model identifier.

    Returns:
        str: Final corrected topic-by-topic course summary and Mermaid concept diagram.
    """
    review_prompt = f"""[SOURCE GROUND TRUTH FROM COURSE PDF]
{source_content}

============================================================
[DRAFT RECAP TO BE AUDITED]
{draft_recap}
============================================================

Review and verify the draft recap against the source ground truth.
Correct any factual errors or hallucinated concepts.
Verify and correct the Mermaid concept diagram.
Output the complete, final polished course recap in GitHub-flavored Markdown.
"""

    interaction = client.interactions.create(
        model=model,
        system_instruction=COURSE_REVIEWER_SYSTEM_PROMPT,
        input=review_prompt,
    )

    if not interaction.output_text:
        raise RuntimeError("course-reviewer sub-agent did not produce any output text.")

    return interaction.output_text.strip()
